# train_config.yaml

train_config_path: "./YOLO_V2_from-scratch/configs/train_config.yaml"
img_dir: "./data/VOCdevkit/VOC2012/JPEGImages"
label_dir: "./data/VOCdevkit/VOC2012/labels"
val_path: "./data/csv/val.csv"
train_path: "./data/csv/train.csv"

load_model_file: "./YOLO_V2_from-scratch/models/overfit.pth.tar"

lr: 0.00002
device: "cuda"
batch_size: 16
epochs: 10
n_works: 2
seed: 123
load_model: false
weight_decay: 0.0
pin_memory: true

