# train_config.yaml

train_config_path: "./YOLO_V1_from-scratch/configs/train_config.yaml"
img_dir: "./data/images"
label_dir: "./data/labels"
test_path: "./data/8examples.csv"
train_path: "./data/100examples.csv"

load_model_file: "./YOLO_V1_from-scratch/models/overfit.pth.tar"

lr: 0.00002
device: "cuda"
batch_size: 16
epochs: 10
n_works: 2
seed: 123
load_model: false
weight_decay: 0.0
pin_memory: true

