# train_config.yaml

train_config_path: "./YOLO_V1_from-sratch/configs/train_config.yaml"
img_dir: "./YOLO_V1_from-sratch/data/images"
label_dir: "./YOLO_V1_from-sratch/data/labels"
test_path: "./YOLO_V1_from-sratch/split_ratio/test.csv"
dataset_ex_dir: "./YOLO_V1_from-sratch/data/100examples.csv"

load_model_file: "./YOLO_V1_from-sratch/overfit.pth.tar"

lr: 0.00002
device: "cuda"
batch_size: 16
epochs: 10
n_works: 2
seed: 123
load_model: false
weight_decay: 0.0
pin_memory: true

